### ISSUE TITLE
Use one RoactHooks instance

### ISSUE THREAD

**Issue by passhley** [vocksel/flipbook#47]
Currently at the bottom of every hooked component we create a new RoactHooks instance. a better way to do this is to store a module named ``hook`` that just returns ``RoactHooks.new(Roact)`` so that way you're not making mulitple RoactHooks instances and then you can just do return ``hook(Component)``

**Comment by vocksel** [comment]
I'm leaning towards not doing this. I started making this port locally and I found that this change does not add much value. In particular this is because:
1. Including a `hook` singleton results in the same number of requires from each file
2. Swapping `RoactHooks.new(Roact)(Story)` with `hook(Story)` for the return statement adds an extra layer of abstraction which I'm not fond of. Having to check `hook.lua` to see what it's doing adds an extra step when right now you can see how Roact/RoactHooks interact with each other in component
3. Creating a new instance of RoactHooks doesn't have any impact on the plugin's performance from what I can tell, so it's fine to create a ton of them

**Comment by vocksel** [comment]
I realized we should be able to use a singleton RoactHooks instance inside of all of our hooks, which removes the need to pass in `hooks` as the first prop. If this works like I expect, then we can move ahead with this change

**Comment by passhley** [comment]
Any updates regarding this?
