### ISSUE TITLE
Stories aren't reloading

### ISSUE THREAD

**Issue by passhley** [vocksel/flipbook#98]
Unsure if this is just a one off bug or something todo with me, but it seems like none of my stories are reloading. I have to open and close the entire plugin to preview my component's changes.

On top of this, I think it'd be a good idea to be allowed to deselect stories you're previewing to go back to the NoStorySelected view.

**Comment by vocksel** [comment]
I've narrowed this down to the ModuleLoader class and how caching is handled. This might be something that needs to be fixed in the underlying package. Still need to investigate further.

Also an interesting quirk: if you comment out `loader:clear()` in `useStorybooks.lua`, then stories don't load at all! No clue why!
